version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_pizzaria
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pizzaria123
      POSTGRES_DB: madre_querida_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Esta linha abaixo é a "mágica": ela liga sua pasta local ao banco
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ../database/seed_motoboys.sql:/docker-entrypoint-initdb.d/03_seed_motoboys.sql

volumes:
  postgres_data:
